### ISSUE TITLE
tableby: Add level to variable label when using cat.simplify

### ISSUE THREAD

**Issue by overdodactyl** [mayoverse/arsenal#288]
When using `cat.simplify`, it would be really convenient if there was an option to include the 
reference level in parenthesis after the label.  

I find myself often having a label/variable name will be something like `Gender`, and when using `cat.simplify`, the information on what is actually getting displayed gets lost.  

It would be nice if this info could get incorporated without having to change the label manually/externally.

Consider this example:

``` r
df <- data.frame(
  Group = sample(c("Controls", "Cases"), 100, TRUE),
  Gender = sample(c("Male", "Female"), 100, TRUE)
)

tbl <- arsenal::tableby(Group ~ Gender, cat.simplify = TRUE, data = df)
summary(tbl, text = TRUE)
#> 
#> 
#> |       | Cases (N=51) | Controls (N=49) | Total (N=100) | p value|
#> |:------|:------------:|:---------------:|:-------------:|-------:|
#> |Gender |  19 (37.3%)  |   24 (49.0%)    |  43 (43.0%)   |   0.236|
```

<sup>Created on 2020-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This feature request would give an output instead like this:

``` r
#> 
#> 
#> |           | Cases (N=51) | Controls (N=49) | Total (N=100) | p value|
#> |:------|:------------:|:---------------:|:-------------:|-------:|
#> |Gender (Male) |  19 (37.3%)  |   24 (49.0%)    |  43 (43.0%)   |   0.236|
```

**Comment by overdodactyl** [comment]
Hmm.  Thinking about this more, if it were to be implemented I guess it would only make sense if it were a per-variable option.  `Diabetes (1)`, for example, probably isn't ideal.

**Comment by eheinzen** [comment]
Yeah, it'd have to be on a per-variable basis, at which point why not just set the labels?
```
> library(arsenal)
> df <- data.frame(
+     Group = sample(c("Controls", "Cases"), 100, TRUE),
+     Gender = sample(c("Male", "Female"), 100, TRUE)
+ )
> 
> tbl <- tableby(Group ~ Gender, cat.simplify = TRUE, data = set_labels(df, c(Gender = "Gender (Male)")))
> summary(tbl, text = TRUE)


|              | Cases (N=52) | Controls (N=48) | Total (N=100) | p value|
|:-------------|:------------:|:---------------:|:-------------:|-------:|
|Gender (Male) |  26 (50.0%)  |   24 (50.0%)    |  50 (50.0%)   |   1.000|
```

**Comment by overdodactyl** [comment]
Initial rational for not changing labels was just a matter of convenience; I find myself needing to add the factor level on rather frequently and was thinking it would be nice to have a built in option so it didn't need to be done manually (particularly for longer tables with lots of cases like this).  

Solution exists though, so feel free to close.
