### ISSUE TITLE
Single Line Results

### ISSUE THREAD

**Issue by emmanuels7** [mayoverse/arsenal#290]
Hi My friend. Great Job with this package !.

Do we have a way of obtaining all the results in a sinlge line instead of row by row ?

Regards

**Comment by eheinzen** [comment]
I'm not quite sure what you're asking for.  Could you give me an example?  Which function in the package?

**Comment by emmanuels7** [comment]
Thanks for your response.

Instead of several singe rows per variable:
Variable:                                                Strata                                                   p-value
|**Fumus**                                          |                   |                                    |    0.620^1^  |
|&nbsp;&nbsp;&nbsp;Count                |         5         |        16                      |        21         |   
|&nbsp;&nbsp;&nbsp;median(IQR)      | 31.0 (29.8, 34.4) | 30.4 (26.5, 37.8) | 30.5 (29.0, 37.3) |   

Obtain one single row combining al the statistics:  
Variable                                              Strata                                                               p-value
|**Fumus** (Count) (median)(IQR)       |  5,  31.0 (29.8, 34.4) | 16, 30.4  (26.5, 37.8  |  0.620^1^|


Regards

**Comment by eheinzen** [comment]
This is possible, but you're kind of on your own for the formatting--`tableby()` wasn't built for things like this. Here's one possibility:

```

NmedianIQR <- function(x, ...)
{
  n <- length(x)
  med <- formatC(median(x), digits = 3, format = "f")
  iqr <- formatC(quantile(x, c(0.25, 0.75)), digits = 3, format = "f")
  
  paste0(n, ", ", med, " (", iqr[1], ", ", iqr[2], ")")
}

summary(tableby(sex ~ age, data = mockstudy, numeric.stats = "NmedianIQR", numeric.simplify = TRUE),
        labelTranslations = list(age = "Age: N, median (Q1, Q3)"))
#
# |                            |         Male (N=916)         |        Female (N=583)        |        Total (N=1499)         | p value|
# |:---------------------------|:----------------------------:|:----------------------------:|:-----------------------------:|-------:|
# |**Age: N, median (Q1, Q3)** | 916, 61.000 (53.000, 69.000) | 583, 60.000 (52.000, 68.000) | 1499, 61.000 (52.000, 68.000) |   0.048|
#
```
