### ISSUE TITLE
Possibility to adjust font size or term column?

### ISSUE THREAD

**Issue by abruegger** [mayoverse/arsenal#292]
I just started using the arsenal package and am very happy with it!

One issue that I cannot solve is that the columns containing the stats in a `tableby` summary table are too narrow for their content (see screenshot). I was wondering if there's an option to do either of the following to make the table prettier:

- Make the term column (column 1) narrower (without deleting words in the question)
- Use a fix minimal width for columns 2-7
- Decrease the font size
- Change the digits in `range` (Wertebereich in German) to none

I would very much appreciate some tips as how to make this table more presentable.

![Screenshot 2020-04-21 at 06 18 54](https://user-images.githubusercontent.com/31000762/79825256-db8dea80-8398-11ea-8dda-0d75b9d889e3.png)

**Comment by eheinzen** [comment]
You could perhaps try something like `print(summary(tableby(...)), width = 30)`, which will attempt to make your label column narrower.

Working example:
```
> library(arsenal)
> m <- set_labels(mockstudy, c(age = "a really really really long label for the age column"))
> tb <- summary(tableby(sex ~ age, data = m), text = TRUE)
> print(tb, width = 10)


|             |  Male (N=916)   | Female (N=583)  | Total (N=1499)  | p value|
|:------------|:---------------:|:---------------:|:---------------:|-------:|
|a really     |                 |                 |                 |   0.048|
|really       |                 |                 |                 |        |
|really       |                 |                 |                 |        |
|long         |                 |                 |                 |        |
|label for    |                 |                 |                 |        |
|the age      |                 |                 |                 |        |
|column       |                 |                 |                 |        |
|-  Mean (SD) | 60.455 (11.369) | 59.247 (11.722) | 59.985 (11.519) |        |
|-  Range     | 19.000 - 88.000 | 22.000 - 88.000 | 19.000 - 88.000 |        |
```

**Comment by abruegger** [comment]
Solved my problem. Thanks for the quick help, it's very much appreciated (I need to have this ready for a seminar tomorrow)!
