### ISSUE TITLE
shiny using renderTable

### ISSUE THREAD

**Issue by dingying85** [mayoverse/arsenal#293]
I got a problem that If use tableby and use renderTable with pfootnote=TRUE, the tableOutput will not be able to show the footnote. Did anyone has the same issue?

**Comment by eheinzen** [comment]
To get a footnote in R Shiny, you may need to do something like what's mentioned here:
https://stackoverflow.com/questions/28003715/caption-in-rendertable-shiny

Something like this may do the trick:
```
library(shiny)
library(arsenal)
s <- as.data.frame(summary(tableby(sex ~ age, data = mockstudy), text = "html", pfootnote = TRUE))

shinyApp(
  ui = fluidPage(
    tableOutput("tb")
  ),
  server = function(input, output) {
    output$tb <- renderTable({
      s
    }, caption.width = NULL, caption.placement = "bottom", caption = attr(s, "tests"), sanitize.text.function = identity)
  }
)

```
