### ISSUE TITLE
family = clog not working?

### ISSUE THREAD

**Issue by bethatkinson** [mayoverse/arsenal#294]
tmp <- modelsum(case01~cond1.any1 + cond2.any1,  data=d1, family='clog', strata=match.id)
Error in fitter(X, Y, istrat, offset, init, control, weights = weights,  : 
  NA/NaN/Inf in foreign function call (arg 5)
In addition: Warning messages:
1: In fitter(X, Y, istrat, offset, init, control, weights = weights,  :
  Ran out of iterations and did not converge
2: In fitter(X, Y, istrat, offset, init, control, weights = weights,  :
  Ran out of iterations and did not converge

But if I run it by hand the model  (using the clogit function) it works fine.

**Comment by bethatkinson** [comment]
But 

tmp <- modelsum(case01~cond1.any1 + cond2.any1, data=d1, family='clog', adjust=~strata(match.id))  does work. Maybe just a documentation issue.

**Comment by eheinzen** [comment]
Indeed the second one is the right way to do it.  Update documentation accordingly
