### ISSUE TITLE
Tableby: How can I conduct t.test or Wilcox?

### ISSUE THREAD

**Issue by youngjune29bhak** [mayoverse/arsenal#295]
Dear All, 

I conducted the following.

>mdat <- data.frame( Sex=sample(c("Male", "Female"), 10,replace=TRUE),
                   Age=round(rnorm(10,mean=40, sd=5)),
                   HtIn=round(rnorm(10,mean=65,sd=5)))

>outResp <- tableby(Sex ~ + Age + HtIn, data=mdat)
>tests(outResp)
  Group Variable   p.value             Method
1   Sex      Age 0.0252416 Linear Model ANOVA
2   Sex     HtIn 0.8607002 Linear Model ANOVA

Although LHS has two levels, tableby conducted ANOVA, not t.test (and the p-value was different when I conducted t.test separately)

How can I conduct t.test or Wilcox in tableby?

Regards,

**Comment by eheinzen** [comment]
The ANOVA is equivalent to an equal-variance t-test in the two-group case.  Similarly, the Kruskal-Wallis test is the same as the Wilcoxon in the two-sample case.  See below:

```
> library(arsenal)
> data(mockstudy)
> tb <- tableby(sex ~ age + kwt(bmi), data = mockstudy)
> tests(tb)
  Group Variable      p.value                       Method
1   sex      age 0.0476877833           Linear Model ANOVA
2   sex      bmi 0.0001696052 Kruskal-Wallis rank sum test
> t.test(age ~ sex, data = mockstudy, var.equal = TRUE)

	Two Sample t-test

data:  age by sex
t = 1.9818, df = 1497, p-value = 0.04769
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.01232698 2.40415680
sample estimates:
  mean in group Male mean in group Female 
            60.45524             59.24700 

> wilcox.test(bmi ~ sex, data = mockstudy)

	Wilcoxon rank sum test with continuity correction

data:  bmi by sex
W = 285416, p-value = 0.0001696
alternative hypothesis: true location shift is not equal to 0
```
