### ISSUE TITLE
CRAN Check Failure for Upcoming broom Release

### ISSUE THREAD

**Issue by simonpcouch** [mayoverse/arsenal#296]
Hi there! The broom dev team just ran reverse dependency checks on the upcoming 0.7.0 release of the package and found new errors/test failures for this package. I've pasted the results below, which seem to result from broom no longer exporting the `confint_tidy()` function (for maintainability purposes.)

*   checking tests ...
    ```
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      'confint_tidy' is not an exported object from 'namespace:broom'
      Backtrace:
        1. testthat::expect_identical(...)
       11. arsenal::modelsum(...)
       12. arsenal:::modelsum_guts(...)
       13. broom::confint_tidy
       14. base::getExportedValue(pkg, name)
      
      ══ testthat results  ═══════════════════════════════════════════════════════════
      [ OK: 426 | SKIPPED: 12 | WARNINGS: 12 | FAILED: 2 ]
      1. Error: ordinal works (@test_modelsum.R#213) 
      2. Error: 08/01/2017: Beth Atkinson's subset problem (@test_modelsum.R#359) 
      
      Error: testthat unit tests failed
      Execution halted
    ```

*   checking dependencies in R code ... NOTE
    ```
    Missing or unexported object: ‘broom::confint_tidy’
    ```

I've pasted the most recently exported function definition below as a place to start from in making the necessary fixes—mostly just the base `confint` function with some extra checks.🙂

```
confint_tidy <- function(x, conf.level = .95, func = stats::confint, ...) {
  # avoid "Waiting for profiling to be done..." message for some models
  ci <- suppressMessages(func(x, level = conf.level, ...))

  # protect against confidence intervals returned as named vectors
  if (is.null(dim(ci))) {
    ci <- matrix(ci, nrow = 1)
  }

  # remove rows that are all NA. *not the same* as na.omit which checks
  # for any NA.
  all_na <- apply(ci, 1, function(x) all(is.na(x)))
  ci <- ci[!all_na, , drop = FALSE]
  colnames(ci) <- c("conf.low", "conf.high")
  as_tibble(ci)
}
```

We hope to submit this new version of the package to CRAN in the coming weeks. If you encounter any problems fixing these issues, please feel free to reach out!

**Comment by eheinzen** [comment]
Thanks for the note!  I'll get this fixed shortly.

**Comment by simonpcouch** [comment]
Thanks for getting this fixed so quickly! It seems like this package is still failing on our CRAN revdepchecks. Would you appreciate any support from us in getting this up on CRAN? It looks like your fix doesn't use any specifically 0.7.0 functionality, so you should be able to drop the version >= 0.7.0 requirement and submit as is. :-)

**Comment by eheinzen** [comment]
Oh, I was going to wait until you guys published.  Classic chicken and egg scenario.

The problem (and reason I need to depend on 0.7.0) is with [this line here](https://github.com/mayoverse/arsenal/commit/060e894a344986d1d4f979b94cd3192ff5efd4e3#diff-54aaec70c6d3b75af011ff480dae4ea9L118): the returned column name for "coefficient type" changed in 0.7.0.  So even if I remove the confint_tidy, `arsenal` would still be marked as failing on CRAN.  I'm not experienced enough with CRAN to know: how are these issues usually resolved?

**Comment by simonpcouch** [comment]
Ah, gotcha! Okay, I'll note this in our message to CRAN. Thanks for the quick reply. :-)

**Comment by eheinzen** [comment]
For sure.  I'll be on the lookout for 0.7.0 and republish arsenal ASAP after broom gets accepted.  Thanks! :)

**Comment by simonpcouch** [comment]
0.7.0 is on CRAN! Thanks for your patience!
