### ISSUE TITLE
Make percentages add up to 100%

### ISSUE THREAD

**Issue by guilhermeparreira** [mayoverse/arsenal#297]
Hi guys! First of all I love your package, and thanks for improvements that you guys have already done before.

Today, when I presented a table, a guy noticed that the sum of the percentages did not add up to 100% (I explained to him, etc...) . This is a boring stuff, but some people care about it, and others may take some benefit of it, [92k views on this question](https://stackoverflow.com/questions/13483430/how-to-make-rounded-percentages-add-up-to-100).

Could you guys add this feature?

##### Observed behaviour

`data <- structure(list(renda_familia = structure(c(2L, 2L, 3L, 4L, 1L, 
3L, 2L, 2L, 2L, 5L, 1L, 2L, 1L, 3L, 2L, 2L, 3L, 1L, 3L, 3L, 1L, 
3L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 3L, 1L, 1L, 2L, 1L, 3L, 2L, 1L, 
3L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 3L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 
3L, 2L, 2L, 1L, 3L, 3L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 2L, 3L, 
2L, 2L, 3L, 3L, 1L, 5L, 1L, 1L, 3L, 2L, 1L, 2L, 1L, 2L, 1L, 1L, 
1L, 1L, 2L, 1L, 2L, 2L, 3L, 3L, 2L, 1L, 4L, 2L, 1L, 3L, 1L, 1L, 
2L, 1L, 5L, 5L, 1L, 2L, 1L, 2L, 2L, 4L, 1L, 2L, 3L, 1L, 5L, 1L, 
1L, 4L, 1L, 1L, 2L, 3L, 3L, 1L, 3L, 3L, 3L, 2L, 2L, 1L, 2L, 2L, 
2L, 1L, 5L, 1L, 2L, 2L, 1L, 1L, 3L, 1L, 2L, 2L, 3L, 1L, 1L, 2L, 
2L, 3L, 1L, 1L, 2L, 3L, 1L, 2L, 2L, 5L, 2L, 1L, 2L, 1L, 2L, 2L, 
2L, 2L, 1L, 2L, 2L, 2L, 2L, 2L, 3L, 2L, 2L, 2L, 1L, 1L, 2L, 1L, 
1L, 2L, 1L, 4L, 1L, 1L, 1L, 1L, 2L, 3L, 1L, 3L, 5L, 1L, 2L, 3L, 
2L, 1L, 3L, 1L, 1L, 1L, 2L, 3L, 3L, 2L, 3L, 2L, 2L, 1L, 3L, 2L, 
1L, 2L, 2L, 1L, 2L, 3L, 2L, 1L, 3L, 2L, 1L, 2L, 2L, 3L, 1L, 2L, 
1L, 1L, 2L, 2L, 3L, 1L, 1L, 2L, 1L, 2L, 2L, 3L, 4L, 2L, 3L, 1L, 
3L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 3L, 3L, 1L, 4L, 3L, 1L, 1L, 3L, 
3L, 5L, 1L, 2L, 2L, 5L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 2L, 3L, 2L, 
5L, 3L, 1L, 3L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 1L, 2L, 
3L, 2L, 1L, 5L, 2L, 1L, 1L, 3L, 2L, 1L, 2L, 2L, 2L, 3L, 2L, 1L, 
3L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 2L, 5L, 1L, 1L, 1L, 2L, 2L, 
2L, 2L, 2L, 1L, 2L, 2L, 2L, 3L, 3L, 3L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 1L, 3L, 1L, 3L, 1L, 2L, 3L, 3L, 1L, 4L, 3L, 2L, 1L, 2L, 
3L, 3L, 2L, 3L, 4L, 1L, 3L, 3L, 1L, 1L, 2L, 1L, 2L, 4L, 1L, 3L, 
3L, 2L, 3L, 3L, 2L, 2L, 3L, 1L, 2L, 2L, 5L, 3L, 2L, 2L, 2L, 1L
), .Label = c("Até 2 S.M.", "2 a 4 S.M.", "4 a 10 S.M.", ">10 S.M.", 
"NR"), class = "factor")), class = "data.frame", row.names = c(NA, 
-389L))`

`tab.noby <- tableby(~ renda_familia, data=data, control = mycontrols)`
`summary(tab.noby)`

renda_familia |  
Até 2 S.M.      | 131 (33.7%)
2 a 4 S.M.      | 156 (40.1%)
4 a 10 S.M.    | 78 (20.1%)
10 S.M.          | 10 (2.6%)
NR                 | 14 (3.6%)

Percentages (%) add to 100.1%

##### Expected behaviour

Até 2 S.M.   | 131 (33.7%)
2 a 4 S.M.   | 156 (40.1%)
4 a 10 S.M. | 78 (20.**0**%)
10 S.M.       | 10 (2.6%)
NR              | 14 (3.6%)

I used this function to create the percentages up to 100%:

`round_sum <- function(x, digits = 0) {
  up <- 10 ^ digits
  x <- x * up
  y <- floor(x)
  indices <- tail(order(x - y), round(sum(x)) - sum(y))
  y[indices] <- y[indices] + 1
  y / up
}`
`vec <- c(131,156,78,10,14)/389`
`round_sum(vec*100,1)`

Thanks in advance!!

**Comment by eheinzen** [comment]
After some internal debate, we decided this isn't a change we feel comfortable making.  If you want to fix your tables, consider using something like

```
as.data.frame(summary(tableby(sex ~ age, data = mockstudy)))
```

and then do some post-processing.  Sorry about that :(

**Comment by guilhermeparreira** [comment]
Thanks for the return @eheinzen !
As far from my knowledge I don't know which approach is better. I think that in this case there is no perfect solution. 
It varies person by person...
