### ISSUE TITLE
adding arsenal tables to jamovi

### ISSUE THREAD

**Issue by sbalci** [mayoverse/arsenal#298]
Dear developers,
I am trying to add `arsenal` tables into [jamovi](https://www.jamovi.org/) in the [ClinicoPath module](https://sbalci.github.io/ClinicoPathJamoviModule/).

Users are informed that `arsenal` package is used and citation is given with each analysis. I would like to ask your help regarding `pfootnotes`. 

- Screenshots of output:

<img width="1235" alt="Ekran Resmi 2020-06-18 13 26 17" src="https://user-images.githubusercontent.com/7208830/85009669-820f2580-b167-11ea-8186-f91ab23af3f4.png">
<img width="1265" alt="Ekran Resmi 2020-06-18 13 26 43" src="https://user-images.githubusercontent.com/7208830/85009680-85a2ac80-b167-11ea-8f29-63ee5a895558.png">

- The code I use is:

```r
                tablearsenal <- arsenal::tableby(formula = formula,
                                                 data = mydata,
                                                 total = TRUE,
                                                 digits = 1,
                                                 digits.count = 1
                )

                tablearsenal <- summary(tablearsenal,
                                        text = 'html',
                                        pfootnote = TRUE
                                        )


                tablearsenal <-
                    kableExtra::kable(tablearsenal,
                                      format = "html",
                                      digits = 1,
                                      escape = FALSE
                                      )

```

- My issue is that: Although I use `pfootnote = TRUE` I could not get it work with `kable`. The output does not give test names.

- I assume since the names of tests are outside `</table>`, the `kable` function does not return them in the output.
The `summary` produces following:

```
   <td style="text-align:center;"> 122 (49.2%) </td>
   <td style="text-align:right;">  </td>
  </tr>
</tbody>
</table>
1. Linear Model ANOVA
2. Pearson's Chi-squared test
```

As a note I tried other output options but I could avoid `&nbsp;` blank spaces only with `kable`.

Would you please guide me in adding the test names to the output?

Best wishes and thank you for the package.

**Comment by eheinzen** [comment]
Try this:

```
summary(tableby(sex ~ age + arm, data = mockstudy), text = "html", pfootnote = "html")
```

Does that work?

**Comment by sbalci** [comment]
Thank you.

Now, the footnote is `html` tagged. However since it is below `</table>` it is still not added to table output.

In R markdown the results are also separated. Table is in `knit_asis` part, the footnote is in `R Console` part. 

Is it possible to combine these two summary outputs, the knit_asis part and console part?

Is there any method to do this with R I can try for my case.

Best wishes


```
...
  </tr>
</tbody>
</table>
<ol>
<li>Linear Model ANOVA</li>
<li>Pearson's Chi-squared test</li>
</ol>
```

<img width="574" alt="Ekran Resmi 2020-06-26 16 12 23" src="https://user-images.githubusercontent.com/7208830/85860821-06952000-b7c8-11ea-8d2f-785750546dc0.png">

**Comment by sbalci** [comment]
Using `capture.output()`I have managed to make it work.
Thank you for your time.

<img width="439" alt="Ekran Resmi 2020-06-26 18 17 05" src="https://user-images.githubusercontent.com/7208830/85873857-65639500-b7da-11ea-8af6-8272a1e0f7de.png">

**Comment by eheinzen** [comment]
Oh yes--sorry!  I should've mentioned that you'd probably need `capture.output()`
