### ISSUE TITLE
arsenal::tableby Limiting to one factor per variable

### ISSUE THREAD

**Issue by mufflyt** [mayoverse/arsenal#303]
Dear Mayoverse,

I truly enjoy working with the arsenal package.  It is a fantastic experience and always reliable.  The journal that I submitted to wants only one level for gender.  Instead of listing male and female they want only the female level because they feel that both are redundant.  Is there a way to select only one level of a factor to display with arsenal::tableby?

Thanks again,
Tyler

**Comment by eheinzen** [comment]
Absolutely.  Try this:

```
> library(arsenal)
> data(mockstudy)
> summary(tableby(arm ~ sex, data = mockstudy, cat.simplify = TRUE))


|        | A: IFL (N=428) | F: FOLFOX (N=691) | G: IROX (N=380) | Total (N=1499) | p value|
|:-------|:--------------:|:-----------------:|:---------------:|:--------------:|-------:|
|**sex** |  151 (35.3%)   |    280 (40.5%)    |   152 (40.0%)   |  583 (38.9%)   |   0.190|

```

See also examples in the [vignette](https://mayoverse.github.io/arsenal/articles/tableby.html#for-two-level-categorical-variables-or-one-line-numeric-variables-simplify-the-output-).

**Comment by mufflyt** [comment]
Thank you very much.  I appreciate your instant reply.  


Take care,
Tyler


Sent with BlackBerry Work
(www.blackberry.com)
