### ISSUE TITLE
tableby: Method to apply cat.simplify for select variables

### ISSUE THREAD

**Issue by kentm4** [mayoverse/arsenal#304]
This is a question and a request:

When creating a summary table with `tableby` we can use `cat.simplify = TRUE` to turn categorical variables with 2 levels into one row summary. However, this is applied to all variables. Is there a way to apply this to only certain variables, by inclusion or exclusion? For some tables, we way want 5 variables to be simplified but 2 variables to show the 2 levels.

**Comment by eheinzen** [comment]
Something like this?

```
d <- data.frame(
  y = sample(c("A", "B"), 10, replace = TRUE),
  x1 = sample(c("C", "D"), 10, replace = TRUE),
  x2 = sample(c("E", "F"), 10, replace = TRUE),
  x3 = sample(c("G", "H"), 10, replace = TRUE)
)
summary(tableby(y ~ chisq(x1, cat.simplify = TRUE) + x2 + x3, data = d))
```

You can replace `chisq` with `notest` for no test, or with `fe` for Fisher's exact.

**Comment by eheinzen** [comment]
Or better for your use case, I guess:

```
> summary(tableby(y ~ chisq(x1, cat.simplify = FALSE) + x2 + x3, data = d, cat.simplify = TRUE))
```

**Comment by kentm4** [comment]
Thanks for the quick response! That makes sense. You have to wrap the variable not to be simplified in a specific call.

**Comment by eheinzen** [comment]
Exactly! :)
