### ISSUE TITLE
write2 issues

### ISSUE THREAD

**Issue by farhadsalimi** [mayoverse/arsenal#312]
write2 functions don't work properly if it's run within an rmd.
Files are saved but with no tables in it while the same code works if it's run in an .R file.

**Comment by eheinzen** [comment]
This might be related to rstudio/rmarkdown#1512.  Can you send me a reproducible example and your `sessionInfo()`?  I'm having a hard time reproducing. We did make a major change to `write2()` in a previous version of arsenal, so a few bugs may have crept through.

**Comment by farhadsalimi** [comment]
``` r
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(arsenal)

data(mtcars)

table <- tableby(cyl ~ disp + hp, data = mtcars)
table_summary <- summary(table)

write2word(table_summary,  "mtcars_table.docx")
#> processing file: mtcars_table.docx.Rmd
#> output file: mtcars_table.docx.knit.md
#> /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS mtcars_table.docx.utf8.md --to docx --from markdown+autolink_bare_uris+tex_math_single_backslash --output mtcars_table.docx --highlight-style tango --lua-filter /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rmarkdown/rmd/lua/pagebreak.lua
#> 
#> Output created: mtcars_table.docx

sessionInfo()
#> R version 3.6.3 (2020-02-29)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Catalina 10.15.7
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] arsenal_3.5.0   forcats_0.5.0   stringr_1.4.0   dplyr_1.0.2    
#>  [5] purrr_0.3.4     readr_1.3.1     tidyr_1.1.1     tibble_3.0.3   
#>  [9] ggplot2_3.3.2   tidyverse_1.3.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] tidyselect_1.1.0 xfun_0.16        splines_3.6.3    haven_2.2.0     
#>  [5] lattice_0.20-38  colorspace_1.4-1 vctrs_0.3.2      generics_0.0.2  
#>  [9] htmltools_0.5.0  yaml_2.2.1       survival_3.2-3   rlang_0.4.7     
#> [13] pillar_1.4.6     glue_1.4.1       withr_2.2.0      DBI_1.1.0       
#> [17] dbplyr_1.4.3     modelr_0.1.6     readxl_1.3.1     lifecycle_0.2.0 
#> [21] munsell_0.5.0    gtable_0.3.0     cellranger_1.1.0 rvest_0.3.5     
#> [25] evaluate_0.14    knitr_1.29       fansi_0.4.1      highr_0.8       
#> [29] broom_0.5.6      Rcpp_1.0.5       scales_1.1.1     backports_1.1.9 
#> [33] jsonlite_1.7.0   fs_1.4.1         hms_0.5.3        digest_0.6.25   
#> [37] stringi_1.4.6    grid_3.6.3       cli_2.0.2        tools_3.6.3     
#> [41] magrittr_1.5     crayon_1.3.4     pkgconfig_2.0.3  Matrix_1.2-18   
#> [45] ellipsis_0.3.1   xml2_1.3.1       reprex_0.3.0     lubridate_1.7.8 
#> [49] assertthat_0.2.1 rmarkdown_2.2    httr_1.4.1       R6_2.4.1        
#> [53] nlme_3.1-144     compiler_3.6.3
```

<sup>Created on 2020-10-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by eheinzen** [comment]
Thanks!  But hmm, I still can't seem to reproduce.  "mtcars_table.docx" still has a table in it, no matter what I knit to.  A few more questions:

1. How are you knitting the "parent" document?  Are you using R Studio, or are you using something like `rmarkdown::render()`?
1. Do you still have the same problem if (1) you knit the "parent" document to a different output type; or (2) if you write2 a different type besides Word?
1. What is the result of `rmarkdown::pandoc_version()`?

**Comment by farhadsalimi** [comment]
1. I can confirm that it works if I use rmarkdown::render() or knit the whole document within RStudio, however, it doesn't work if I just run the chunk within the Rmarkdown document.
2. It is the same story for word, html, and pdf
3. 2.3.1

**Comment by eheinzen** [comment]
Ah yes, now we're on to something--thanks!  I can reproduce your issue, but the solution isn't really `arsenal`-related.  Go to Tools > Global Options > R Markdown > "Show output inline for all R Markdown documents" and uncheck it.  Otherwise I think R Studio is doing some black magic and capturing the table output to render it inline.

Let me know if that works

**Comment by farhadsalimi** [comment]
your solution works, thanks. Maybe you can add this as a note to your vignette! :)

**Comment by eheinzen** [comment]
Done!
