### ISSUE TITLE
autofit the table/column width (in PDF output)

### ISSUE THREAD

**Issue by xingzhaofei** [mayoverse/arsenal#313]
Dears,

Could you please let me know that how can we autofit the table/column width for PDF output, espicial in landscape page. 
Is it possible to add this in to write2 function? May be can be incoperated from R package "kableExtra". 
Thank you very much.

Jeffrey

**Comment by eheinzen** [comment]
Something like this works for me:

```
library(arsenal)
library(kableExtra)
tb1 <- tableby(sex ~ age, data = mockstudy) %>%
  summary(text = "latex") %>%
  as.data.frame() %>%
  knitr::kable(format = "latex", escape = FALSE, booktabs = TRUE) %>%
  kable_styling(full_width = TRUE)


write2pdf(list(
  yaml("header-includes" = as.list(kableExtra:::latex_pkg_list())),
  tb1
), "test.pdf", clean = FALSE)
```

**Comment by xingzhaofei** [comment]
Great! Thank you @eheinzen very much. It works!
Another question, can we add the Header and Footer inside the PDF, using like 'fancyhead[CO,CE]'? Thanks.

**Comment by xingzhaofei** [comment]
Great! Thank you @eheinzen very much. It works!

Another question, can we add the Header and Footer inside the PDF, using like 'fancyhead[CO,CE]'? Thanks.


Jeffrey

在 2020-10-15 22:02:22，"Ethan Heinzen" <notifications@github.com> 写道：

Something like this works for me:

library(arsenal)
library(kableExtra)
tb1 <- tableby(sex ~ age, data = mockstudy) %>%
  summary(text = "latex") %>%
  as.data.frame() %>%
  knitr::kable(format = "latex", escape = FALSE, booktabs = TRUE) %>%
  kable_styling(full_width = TRUE)


write2pdf(list(
  yaml("header-includes" = as.list(kableExtra:::latex_pkg_list())),
  tb1
), "test.pdf", clean = FALSE)

**Comment by eheinzen** [comment]
1. Something [like this](https://bookdown.org/yihui/rmarkdown-cookbook/latex-header.html) should work:
```
library(arsenal)
library(kableExtra)
tb1 <- tableby(sex ~ age, data = mockstudy) %>%
  summary(text = "latex") %>%
  as.data.frame() %>%
  knitr::kable(format = "latex", escape = FALSE, booktabs = TRUE) %>%
  kable_styling(full_width = TRUE)


write2pdf(list(
  yaml("header-includes" = as.list(c(
    kableExtra:::latex_pkg_list(),
    "\\usepackage{fancyhdr}",
    "\\pagestyle{fancy}",
    "\\fancyhead[CO,CE]{Your Document Header}"
  ))),
  tb1
), "test.pdf", clean = FALSE)
```

2. Unfortunately, I don't know.
3. This is because of BMI's label.  Try this:
```
library(arsenal)
library(kableExtra)
tb1 <- tableby(arm ~ sex + race + age + ps + hgb + mdquality.s + fu.stat + bmi, data = mockstudy) %>%
  summary(text = "latex", labelTranslations = list(bmi = "Body Mass Index")) %>%
  as.data.frame() %>%
  knitr::kable(format = "latex", escape = FALSE, booktabs = TRUE, longtable = TRUE) %>%
  kable_styling(full_width = TRUE)


write2pdf(list(
  yaml("header-includes" = as.list(c(
    kableExtra:::latex_pkg_list(),
    "\\usepackage{fancyhdr}",
    "\\pagestyle{fancy}",
    "\\fancyhead[CO,CE]{Your Document Header}"
  ))),
  tb1
), "test.pdf", clean = FALSE)
```

**Comment by xingzhaofei** [comment]
Thank you @eheinzen very much!

**Comment by sinnweja** [comment]
Jeffrey, the vignette has the syntax for strata as a separate argument outside the formula in the [example provided](https://cran.r-project.org/web/packages/arsenal/vignettes/modelsum.html#model-data-by-a-non-test-group-strata`).

Note that the strata is a grouping, where treatment arm (arm) or sex would make more sense to stratify on than age. So I would run this:
`summary(modelsum(Surv(fu.time, fu.stat) ~  sex, strata=arm, data=mockstudy, family="survival"))
`
Or maybe most appropriately, this:

`summary(modelsum(Surv(fu.time, fu.stat) ~  sex, strata=arm, adjust= ~age, data=mockstudy, family="survival"))
`

I confirm having a tilde (~) for the adjust argument but not for the strata argument as confusing. Something I'll discuss with @eheinzen

**Comment by sinnweja** [comment]
@bethatkinson reminded me to note that the strata in modelsum will simply perform a separate univariable analysis within each strata, while the strata in a regular coxph will fit an overall effect for the non-stratified variables, but estimate a different baseline hazard for each category in the strata.  So hopefully you are now able to specify the model you truly want to fit.

**Comment by xingzhaofei** [comment]
Thanks Jason.
I want to use mutiple strata in regular coxph, suppose "fit an overall effect for the non-stratified variables, but estimate a different baseline hazard for each category in the strata", I can do it in regular coxph by code like below:
Surv(AVAL, event) ~ strata(BASEBRCA,TRTRESP) + TRTPN
could you please let me konw how to do in modelsum, seems that only one factor in strata= currently? Thank you.


Jeffrey





At 2022-05-26 05:07:56, "Jason Sinnwell" ***@***.***> wrote:

@bethatkinson reminded me to note that the strata in modelsum will simply perform a separate univariable analysis within each strata, while the strata in a regular coxph will fit an overall effect for the non-stratified variables, but estimate a different baseline hazard for each category in the strata. So hopefully you are now able to specify the model you truly want to fit.

**Comment by bethatkinson** [comment]
I don't believe that works currently, but we should add that as a features request.

________________________________
From: xingzhaofei ***@***.***>
Sent: Thursday, May 26, 2022 11:08 AM
To: mayoverse/arsenal ***@***.***>
Cc: Atkinson, Elizabeth J. (Beth), M.S. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [mayoverse/arsenal] autofit the table/column width (in PDF output) (#313)




Thanks Jason.
I want to use mutiple strata in regular coxph, suppose "fit an overall effect for the non-stratified variables, but estimate a different baseline hazard for each category in the strata", I can do it in regular coxph by code like below:
Surv(AVAL, event) ~ strata(BASEBRCA,TRTRESP) + TRTPN
could you please let me konw how to do in modelsum, seems that only one factor in strata= currently? Thank you.


Jeffrey





At 2022-05-26 05:07:56, "Jason Sinnwell" ***@***.***> wrote:

@bethatkinson reminded me to note that the strata in modelsum will simply perform a separate univariable analysis within each strata, while the strata in a regular coxph will fit an overall effect for the non-stratified variables, but estimate a different baseline hazard for each category in the strata. So hopefully you are now able to specify the model you truly want to fit.

**Comment by eheinzen** [comment]
It checks out:

```
> library(arsenal)
> library(survival)
> summary(modelsum(Surv(fu.time, fu.stat) ~ arm, adjust = ~ strata(age, sex), data=mockstudy, family="survival"))


|                            |HR    |CI.lower.HR |CI.upper.HR |p.value |concordance |
|:---------------------------|:-----|:-----------|:-----------|:-------|:-----------|
|**Treatment Arm F: FOLFOX** |0.668 |0.579       |0.770       |< 0.001 |0.555       |
|**Treatment Arm G: IROX**   |0.961 |0.820       |1.127       |0.627   |            |

> coxph(Surv(fu.time, fu.stat) ~ arm + strata(age, sex), data = mockstudy)
Warning: partial match of 'std' to 'std.err'
Warning: partial match of 'std' to 'std.err'
Call:
coxph(formula = Surv(fu.time, fu.stat) ~ arm + strata(age, sex), 
    data = mockstudy)

                 coef exp(coef) se(coef)      z            p
armF: FOLFOX -0.40371   0.66784  0.07240 -5.576 0.0000000246
armG: IROX   -0.03949   0.96127  0.08129 -0.486        0.627

Likelihood ratio test=40.14  on 2 df, p=0.000000001921
n= 1499, number of events= 1356 

```

**Comment by xingzhaofei** [comment]
Great. Thank you all very much. 
It works by using "adjust = ~ strata(category1, category2)". ^_^



At 2022-05-27 02:24:07, "Ethan Heinzen" ***@***.***> wrote:

It checks out:

> library(arsenal)
> library(survival)
> summary(modelsum(Surv(fu.time, fu.stat) ~ arm, adjust = ~ strata(age, sex), data=mockstudy, family="survival"))


|                            |HR    |CI.lower.HR |CI.upper.HR |p.value |concordance |
|:---------------------------|:-----|:-----------|:-----------|:-------|:-----------|
|**Treatment Arm F: FOLFOX** |0.668 |0.579       |0.770       |< 0.001 |0.555       |
|**Treatment Arm G: IROX**   |0.961 |0.820       |1.127       |0.627   |            |

> coxph(Surv(fu.time, fu.stat) ~ arm + strata(age, sex), data = mockstudy)
Warning: partial match of 'std' to 'std.err'
Warning: partial match of 'std' to 'std.err'
Call:
coxph(formula = Surv(fu.time, fu.stat) ~ arm + strata(age, sex), 
    data = mockstudy)

                 coef exp(coef) se(coef)      z            p
armF: FOLFOX -0.40371   0.66784  0.07240 -5.576 0.0000000246
armG: IROX   -0.03949   0.96127  0.08129 -0.486        0.627

Likelihood ratio test=40.14  on 2 df, p=0.000000001921
n= 1499, number of events= 1356
