### ISSUE TITLE
How to number the tables from `summary.tableby()` in rmarkdown html output documment.

### ISSUE THREAD

**Issue by guilhermeparreira** [mayoverse/arsenal#314]
Hi There! When I use `bookdown::html_document2:` the tables from `kable` are numbered automatically. I wonder whether there is a way to also number the tables from `summary.tableby()` (preferable) or some mechanism like that. Or even, to obtain the table before the `printing` and doing the `kable` by myself.

**Comment by eheinzen** [comment]
Have you tried downloading the GitHub version?  I made some changes in #310 that might affect the answer to this

**Comment by guilhermeparreira** [comment]
It works. Thanks! It can be closed

**Comment by eheinzen** [comment]
Great! 👍

**Comment by guilhermeparreira** [comment]
Hi @eheinzen!

When I try to refer a table from `summary.tableby(..., label = "table1")` in a text like `\@ref(tab:table1)` it does not work. With pure `kable` it works. I am outputting it to `  bookdown::html_document2:`. Could you have a look please?

**Comment by bethatkinson** [comment]
Using bookdown I've done the following:

However, as is shown in Table ***@***.***(tab:flc-tab1), the age and sex distribution differs by FLC group.

```{r tab:flc-tab1, results='asis'}
mycont <- tableby.control(numeric.stats=c('Nmiss','medianq1q3'))
tab1 <- tableby(group ~ age + sex, data=flchain2, control=mycont)
summary(tab1, total=F, test=F, digits=0,
        title='Baseline summary of the Free Light Chain cohort stratified by levels of FLC')
```

________________________________
From: Guilherme Parreira ***@***.***>
Sent: Friday, March 19, 2021 5:16 PM
To: mayoverse/arsenal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [mayoverse/arsenal] How to number the tables from `summary.tableby()` in rmarkdown html output documment. (#314)


Hi @eheinzen<https://github.com/eheinzen>!

When I try to refer a table from summary.tableby(..., label = "table1") in a text like ***@***.***(tab:table1) it does not work. With pure kable it works. I am outputting it to bookdown::html_document2:. Could you have a look please?

**Comment by eheinzen** [comment]
Make [sure you're using a caption ("title")](https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html#cross-ref) as well, and then pass the `label=` argument to the `print()` function:
````
```{r results='asis'}
library(arsenal)

tab <- summary(tableby(sex ~ age, data = mockstudy), title = "hi there")
print(tab, label = "table1")
```

In table \@ref(tab:table1), we see...
````
