### ISSUE TITLE
tableby requires survival

### ISSUE THREAD

**Issue by tdeenes** [mayoverse/arsenal#317]
The **survival** package is only a suggested package, but the `tableby` function calls `survival::is.Surv(currcol)`. Either `if (!requireNamespace("survival", quietly)) ...` should be called or the **survival** package must be placed to Imports in the description file.

**Comment by eheinzen** [comment]
Usually `survival` ships with base R, but touché!  I've been using `::` sloppily for my suggests.  Should be fixed now, with informative errors.
