### ISSUE TITLE
When I do a "26. Tabulate data by a non-test group (strata)" it shows a lot of undesired zero counts

### ISSUE THREAD

**Issue by guilhermeparreira** [mayoverse/arsenal#318]
Hi There. I have a number of cities with its neighbors. So, I want to show which neighbor is in every city:
`
df <- structure(list(Municipio = c("CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", NA, "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", "CWB", 
"CWB", "CWB", "CWB", "ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", 
"ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", 
"ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", 
"ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", "ARAUCÁRIA", 
"ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", 
"ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", 
"ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", 
"ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", 
"ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", 
"ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", "ALMIRANTE TAMANDARÉ", 
"ALMIRANTE TAMANDARÉ", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", 
"CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", 
"CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", 
"CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", 
"CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", "CAMPO LARGO", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", "SÃO JOSÉ DOS PINHAIS", 
"PINHAIS", "PINHAIS", "PINHAIS", "PINHAIS", "PINHAIS", "PINHAIS", 
"PINHAIS", "PINHAIS", "PINHAIS", "PINHAIS", "PINHAIS", "PINHAIS", 
"PINHAIS", "PINHAIS", "PINHAIS", "PINHAIS", "PIRAQUARA", "PIRAQUARA", 
"PINHAIS", "COLOMBO", "COLOMBO", "COLOMBO", "COLOMBO", "COLOMBO", 
"COLOMBO", "COLOMBO", "PINHAIS", "COLOMBO"), Bairro = c(NA, NA, 
"CAMPO SANTANA", "CIC", "CAPÃO RASO", NA, "CAMPO DO SANTANA", 
"NOVO MUNDO", NA, "TATUQUARA", "CIC", NA, "PINHEIRINHO", NA, 
NA, "CIC", "FAZENDINHA", NA, NA, "BOQUEIRÃO", NA, NA, "CAMPO DO SANTANA", 
NA, "CIC", NA, NA, NA, NA, NA, NA, "TATUQUARA", NA, "FAZENDA RIO GRANDE", 
NA, NA, "PINHEIRINHO", NA, NA, "CIC", NA, NA, "TATUQUARA", NA, 
NA, NA, NA, NA, NA, "PIEN", NA, NA, "GANCHINHO", "CAIUA", NA, 
NA, "PIEN", NA, NA, "CENTRO", "CAPÃO DA IMBUIA", "BIGORRILHO", 
NA, NA, NA, NA, "REBOUÇAS", "CAJURU", NA, NA, NA, NA, NA, "CAMPO COMPRIDO", 
"TARUMÃ", NA, "JARDIM DAS AMERICAS", NA, NA, "UBERABA", "CAJURU", 
NA, NA, NA, NA, NA, "PINHAIS", NA, "TARUMÃ", "ALTO DA XV", NA, 
NA, "SITIO CERCADO", NA, "GUAIRA", NA, NA, NA, "ALTO BOQUEIRÃO", 
NA, "UMBARA", "SITIO CERCADO", NA, "BOQUEIRÃO", NA, "SC", "SC", 
"PINHEIRINHO", NA, "SC", "PORTÃO", NA, NA, NA, NA, NA, "XAXIM", 
NA, NA, "BOQUEIRÃO", NA, NA, "SITIO CERCADO", "GANCHINHO", NA, 
NA, NA, "CAJURU", "BOQUEIRÃO", NA, "GUAIRA", NA, "SITIO CERCADO", 
NA, "PAROLIN", "PAROLIN", NA, "CAJURU", "BOQUEIRÃO", NA, "PAROLIN", 
"REBOUÇAS", "BOQUEIRÃO", "COLOMBO", "PAROLIN", "CENTRO", "CAPÃO RASO", 
"UBERABA", NA, "BOQUEIRÃO", "BOM RETIRO", "SITIO CERCADO", NA, 
NA, NA, NA, "CAPÃO DA IMBUIA", NA, NA, NA, NA, "CAMPO DE SANTANA", 
"FAZENDA RIO GRANDE", "CIC", NA, NA, NA, "GUAIRA", NA, NA, "AGUA VERDE", 
NA, NA, NA, "TATUQUARA", "PORTÃO", NA, "FAZENDINHA", NA, NA, 
"CIC", NA, "MERCES", "FAZENDINHA", "BATEL", NA, NA, NA, NA, NA, 
NA, "CAMPO COMPRIDO", "BACACHERI", "CIC", NA, NA, NA, NA, "FAZENDINHA", 
NA, "CIC", "CAMPINA DO SIQUEIRA", NA, NA, "CASCATINHA", "CAMPO COMPRIDO", 
"BACACHERI", NA, NA, "AUGUSTA", NA, NA, NA, "PILARZINHO", NA, 
NA, NA, NA, "SANTA QUITERIA", "CAMPO COMPRIDO", NA, NA, NA, NA, 
NA, NA, NA, NA, NA, "BOA VISTA", NA, NA, "CABRAL", "SANTA CANDIDA", 
NA, NA, NA, NA, NA, NA, NA, NA, "COLOMBO", NA, "CENTRO", "BV", 
NA, NA, NA, NA, "SANTA CANDIDA", NA, NA, NA, NA, "PINHAIS", "BACACHERI", 
NA, NA, "PILARZINHO", NA, NA, NA, NA, NA, NA, NA, NA, NA, "CENTRO", 
NA, NA, NA, "Tupy", NA, NA, NA, NA, "CACHOEIRA", NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, "ITAQUI", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, "RIVABEN", NA, "ACACIA", "BOM JESUS", NA, "SANTA RITA", 
"JARDIM", "BORDA", NA, "Rio Pequeno", NA, NA, NA, NA, NA, NA, 
"BONECA IGUACU", NA, NA, "CENTRO", "COLONIA MURICY", NA, NA, 
NA, NA, "SANTO ANTONIO", NA, "SÃO PEDRO", NA, NA, NA, NA, "OURO FINO", 
"JARDIM ALEGRIA", NA, NA, "Rio Pequeno", NA, NA, "AFONSO PENA", 
"JARDIM AEROPORTO", NA, NA, NA, NA, "MARACANÃ", NA, NA, "VILA MACEDO", 
NA, NA, NA, "PALOMA", NA, NA, NA, NA, NA, NA, "CENTRO", "GUABIROTUBA", 
NA, NA, NA, NA, "GUABIROTUBA", NA, NA, "ALTO MARACANA", NA, NA, 
"GUABIROTUBA", NA)), row.names = c(NA, -388L), class = c("tbl_df", 
"tbl", "data.frame"))
`

`
library(arsenal)
summary(tableby( ~ Bairro, strata = Municipio, data = df))
`

I get (this is only the first lines of the table):

![image](https://user-images.githubusercontent.com/13880005/99799687-d3a24e80-2b11-11eb-9d2b-5551763748a9.png)

I don't want that "ACACIA", "AFONSO PENA", ..., "CAMPO COMPRIDO" all this zero counts to appear under ALMIRANTE TAMANDARE, because they don't belong to ALMIRANTE TAMANDARE. What I need (if it is convenient for you guys) is to show this table "dropping the levels" (so, only showing the counts that really belong to the city).

Thank you in advance.

**Comment by eheinzen** [comment]
Sorry for the delay.  Something like this should do the trick now:
```
  d <- data.frame(
    z = rep(LETTERS[1:3], each = 10),
    x = rep(c("a", "b", "b"), each = 10),
    y = rep(LETTERS[1:3], times = 10),
    stringsAsFactors = FALSE
  )
 summary(tableby(y ~ x, data = d, strata = z, cat.droplevels = TRUE), text = TRUE)


# |z  |     |  A (N=10)  |  B (N=10)  |  C (N=10)  | Total (N=30) | p value |
# |:--|:----|:----------:|:----------:|:----------:|:------------:|:-------:|
# |A  |x    |            |            |            |              |         |
# |   |-  a | 4 (100.0%) | 3 (100.0%) | 3 (100.0%) | 10 (100.0%)  |         |
# |B  |x    |            |            |            |              |         |
# |   |-  b | 3 (100.0%) | 4 (100.0%) | 3 (100.0%) | 10 (100.0%)  |         |
# |C  |x    |            |            |            |              |         |
# |   |-  b | 3 (100.0%) | 3 (100.0%) | 4 (100.0%) | 10 (100.0%)  |         |
```

If you also want the p-values, you'll also need `test.always = TRUE`.

**Comment by guilhermeparreira** [comment]
That's cool! Tks Eheinzen. I will try it later on.
