### ISSUE TITLE
Date tolerances not applying

### ISSUE THREAD

**Issue by geneh0** [mayoverse/arsenal#319]
I'm trying to compare the outputs of two data frames from different sources that are to be exact copies of each other. Due to the way one of the variables (`speccollecteddate`) is coded, there tends to be rounding differences between the two dataframes (± 1 day). I'm trying to set a threshold of 1 day, but observations are still not matching up. The dates are rounded to the nearest day using `lubridate` and then converted with `as.Date()`. I've confirmed with `arsenal::is.Date()` that the variable is, in fact, a Date object. I've also confirmed that the other cells (`person_id` to `specimen_cat`) are the same between the two dataframes. 

Example output (from `obs.table`): 

| version | person_id | incident_id | specimen_cat | speccollecteddate | observation |
|---------|-----------|-------------|--------------|-------------------|-------------|
| x       | 123456| 9876543| NAS          | 2020-04-08        | 1           |
| y       | 123456    | 9876543     | NAS          | 2020-04-07        | 1           |

So far, I've tried setting `tol.date.val = 2` in `comparedf()`  as well as  
```
comparedf.control(tol.date = function(x, y, tol) (abs(as.integer(difftime(x, y, units = 'days'))) > tol),
    tol.date.val = 2)
```

without any luck.

What I found interesting was that even if I try to set the complement (i.e. `< tol`), the `obs.table` looks exactly the same.

**Comment by geneh0** [comment]
I think I was misunderstanding the application of `obs.table`

**Comment by eheinzen** [comment]
Sorry for dropping the ball on this.

You're right that `obs.table` is not the right place to be looking (it reports observations which are not shared between the two data.frames, but not whether the observations' other data are the same).  Instead, consider the `diffs.table` element, or just use `diffs()` to extract differences:

```
> a <- data.frame(x = Sys.Date() + 1)
> b <- data.frame(x = Sys.Date())
> library(arsenal)

> # no differences
> diffs(summary(comparedf(a, b, tol.date.val = 1)))
[1] var.x         var.y         ..row.names.. values.x      values.y      row.x         row.y        
<0 rows> (or 0-length row.names)

> # now there are differences
> diffs(summary(comparedf(a, b, tol.date.val = 0)))
  var.x var.y ..row.names..   values.x   values.y row.x row.y
1     x     x             1 2020-12-03 2020-12-02     1     1
```

Note also that the tolerances are not applied to the "by" variables (that is, there's no fuzzy merging).  It looks like your date is one of them, so it's not going to pick up on that.
