### ISSUE TITLE
Additional features for tableby.control

### ISSUE THREAD

**Issue by dchiu911** [mayoverse/arsenal#320]
I would appreciate if the following additional features could be added:
- a name for the column header. Currently it is an empty string but I want to call it "Variable". An additional parameter analogous to `test.pname` but instead `var.name` with default "" could work?
- position for the Total column. For very wide tables, I don't want to always scroll to the very right to see the Total column. It would be nice if I could place it the leftmost. An additional parameter like `total.pos` with default "right" could work?
```r
mdat <- data.frame(
  Response = c(0, 0, 0, 0, 0, 1, 1, 1, 1, 1),
  Sex = sample(c("Male", "Female"), 10, replace = TRUE),
  Age = round(rnorm(10, mean = 40, sd = 5)),
  HtIn = round(rnorm(10, mean = 65, sd = 5))
)
outResp <-
  tableby(
    Response ~ Sex + Age + HtIn,
    data = mdat,
    total = FALSE,
    test = TRUE,
    test.pname = "p-value"
  )
names(as.data.frame(summary(outResp)))
#> [1] ""             "0 (N=5)"      "1 (N=5)"      "Total (N=10)" "p-value"     
```
I want to be able to get without post-processing the following:
```r
#> [1] "Variable"      "Total (N=10)"        "0 (N=5)"      "1 (N=5)"      "p-value"     
```

**Comment by eheinzen** [comment]
The first is poorly documented, but should work with something like
```
summary(tableby(sex ~ arm, data = mockstudy), term.name = "Variable")
```

The second I should be able to implement.

**Comment by dchiu911** [comment]
Any updates on the second feature?

**Comment by eheinzen** [comment]
Thanks for your patience--between the holidays and other work, I haven't gotten around to this until just now.  Try this:

```
summary(tableby(sex ~ age, data = mockstudy, strata = arm, total.pos = "before"), text = TRUE)
```
