### ISSUE TITLE
Displaying a column for which the grouping variable == NA

### ISSUE THREAD

**Issue by alexflaris** [mayoverse/arsenal#330]
Hello again,

For function ```tableby```, is there a way to display a column for which the grouping variable = ```NA```? And have the ```Total``` column include that too?

What I mean is if I call tableby as such:

```Table1 <- tableby(grouping_variable ~ var1 + var2 + var3)```

and ```grouping_variable``` takes on as values ```[0 1 NA]```

I would like to have the following as an output:

```
"|                         |             1          |          0                |          NA               |    Total | p-value|",
 "|:----------------|:-----------------|:------------------|:--------------------:|--------:|---------|",
 "|                         |                         |                           |                               |            |   0.01    |",
 "|:  N                   |        47              |        45               |        42                   |    134   |            |",
```

I can get the total by running:
```Table1 <- tableby(~ var1 + var2 + var3)```

and I can get the non-NAs and NAs by running:
```Table1 <- tableby(is.na(grouping_variable) ~ var1 + var2 + var3)```
which gives three columns (```NA FALSE```, ```NA TRUE``` and ```Total```)

but I don't know how to merge the columns in order to produce a single table.

Is there a way to produce such a table? (by maybe offering an ```na.rm = FALSE``` option in ```tableby.control```?)

Thank you,
Alex

**Comment by alexflaris** [comment]
I actually found a solution this morning.

It suffices to pretreat the data with forcats and name the NA column explicitly:

```my_data %>%
  mutate(gouping_variable = forcats::fct_explicit_na(grouping_variable, na_level = "Missing")) -> my_data_missing

**Comment by eheinzen** [comment]
Fabulous, thanks!  I believe `arsenal::includeNA()` will also do the same.
