### ISSUE TITLE
Kable title and pfootnote do not show up in MS Word Document

### ISSUE THREAD

**Issue by alexflaris** [mayoverse/arsenal#332]
I don't know if this is a bug, but when I run the kable() function inside RStudio, I do get a title and the footnotes.
However, when I knit the exact same code, my table does not have a title nor does it have footnotes (it doesn't even show the superscripts for the p-values).

My settings are:

````
---
output:
  word_document: default
  html_document:
    
    df_print: paged
always_allow_html: true
---

---
title: "Title"
date: "Today"
output:
  word_document:
  pandoc_args: ["--lua-filter=/path/to/pagebreak.lua"]
---

```{r setup , include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      fig.align = "center",
                      fig.width = 4, 
                      fig.height = 4, 
                      dev = "png",
                      cache = TRUE,
                      message = FALSE,
                      warning = FALSE)
```
options(knitr.table.format = 'markdown')
````

I load the ```knitr``` library (but not ```kableExtra``` because it messes up the display on the word documents).

**Comment by eheinzen** [comment]
Let's try a simpler example.  Does this work as a standalone document?

````
---
output:
  word_document: default
title: "Title"
---


```{r results='asis'}
summary(arsenal::tableby(sex ~ age, data = arsenal::mockstudy), pfootnote = TRUE, title = "hi there")
```

````

**Comment by alexflaris** [comment]
Yes it does!

I added ```results='asis'``` in the header.

I used to print the table as:
```kable(summary(...))``` or ```print(summary(...))```

Now that I removed ```kable()``` and ```print()``` and just left ```summary()``` in place it works just fine!

Thank you!
Alex

**Comment by eheinzen** [comment]
Great!

PS. No, not that I'm aware of.  You'd need to use a [Word template](https://bookdown.org/yihui/rmarkdown-cookbook/word-template.html), I think.
