### ISSUE TITLE
display meansd individually

### ISSUE THREAD

**Issue by LW1103** [mayoverse/arsenal#343]
Hi all, 

i want to customize my arsenal table in a way that "meansd" ist not displayed in brackets (for example 57.5 (5.0)), but with a ± as a separator (-> 57.5 ±  5). I tried to define this in tabby.control, but failed. Can anyone help me? 

Thanks in advance! 
LW

**Comment by sinnweja** [comment]
Here is a possible solution. We tried to make it easy to adapt the meansd by users, but it's not entirely straight-forward without a little savviness.  

```
meanpm <- function (x, na.rm = TRUE, weights = NULL, ...) 
{
    y <- if (na.rm && allNA(x)) {
        NA_real_
    }
    else {
        m <- arsenal:::wtd.mean(x, weights = weights, na.rm = na.rm)
        s <- sqrt(arsenal:::wtd.var(x, weights = weights, na.rm = na.rm))
        if (is.Date(x)) 
            list(as.character(m), as.difftime(s, units = "days"))
        else c(m, s)
    }
    arsenal:::as.tbstat(y, parens = c("+/-", ""))
}
```
Then when your function is loaded, an example using mockstudy gives this (sorry if there is poor format on the output):
```
> summary(tableby(arm ~ kwt(age), numeric.stats=c("meanpm","range") , data=mockstudy), digits=1, text=TRUE)
```

> |             | A: IFL (N=428) | F: FOLFOX (N=691) | G: IROX (N=380) | Total (N=1499) | p value|
> |:------------|:--------------:|:-----------------:|:---------------:|:--------------:|-------:|
> |Age in Years |                |                   |                 |                |   0.639|
> |-  meanpm    |  59.7 +/-11.4  |   60.3 +/-11.6    |  59.8 +/-11.5   |  60.0 +/-11.5  |        |
> |-  Range     |  27.0 - 88.0   |    19.0 - 88.0    |   26.0 - 85.0   |  19.0 - 88.0   |        |

**Comment by eheinzen** [comment]
I just added this.  Thanks for the suggestion!

**Comment by eheinzen** [comment]
cc #351 -- coming soon: an easier way to do this
