### ISSUE TITLE
tableby: print medianiqr in the same row 

### ISSUE THREAD

**Issue by vksssag** [mayoverse/arsenal#350]
Hey! 

Is it possible to add a function in the control settings to print medianiqr in the same line?

Thank you!!

**Comment by sinnweja** [comment]
We do provide a function medianq1q3, which gets formatted to "median (q1, q3)". Some people state IQR, but actually mean (no pun intended) the Q1 and Q3.  Either way, if you want "median (IQR)", you can define your own function that looks a little like arsenal:::meansd for the formatting, and arsenal:::medianq1q3 for the calculations needed. We apologize it is not super clean to write your own stat-summary function, but people have had success using the existing functions as templates.

**Comment by vksssag** [comment]
@sinnweja haha I did mean median(iqr) and perfect I will try that myself. May you please direct me to where i can find the templates for those functions?

Thank you!!

**Comment by sinnweja** [comment]
>  R> arsenal:::medianq1q3
function (x, na.rm = TRUE, weights = NULL, ...) 
{
    y <- if (na.rm && allNA(x)) {
        NA_real_
    }
    else wtd.quantile(x, weights = weights, probs = c(0.5, 0.25, 
        0.75), na.rm = na.rm)
    as.tbstat(y, oldClass = if (is.Date(x)) 
        "Date"
    else NULL, parens = c("(", ")"), sep2 = ", ")
}
<bytecode: 0x18971058>
<environment: namespace:arsenal>

**Comment by vksssag** [comment]
Thank you, appreciate your help!
