### ISSUE TITLE
Using tableby in a function or loop

### ISSUE THREAD

**Issue by kivanvan** [mayoverse/arsenal#356]
I really like the `tableby()` and I use it a lot in my work. Recently, I wanted to use the `tableby()`  in a self-defined function, but I failed to refer to the variables in the `tableby()` . 

I wanted to present intensity and inconvenience by group variable. This is my self-defined function:
`inten_incon <- function(symp.name) { inten <- paste("intens", symp.name, sep = "_")  
incon <- paste("incon", symp.name, sep = "_") 
tb4 <- tableby(group ~ inten + incon, data = df, test = F, total = F)  
summary(tb4, digits.pct = 0)}`

And I got this error message: 

> Error in model.frame.default(formula = group ~ inten + incon, data = (function (x, : 
variable lengths differ (found for 'inten')

Is there a way to make it work?

**Comment by eheinzen** [comment]
The problem is that those variables are characters, instead of columns of your data.frame.  Try something like this:

```
inten_incon <- function(symp.name) {
  inten <- paste("intens", symp.name, sep = "_")
  incon <- paste("incon", symp.name, sep = "_")
  tb4 <- tableby(formulize(y = "group", x = c(inten, incon)), data = df, test = F, total = F) # this is the line I changed
  summary(tb4, digits.pct = 0)
}
```

**Comment by kivanvan** [comment]
> tb4 <- tableby(formulize(y = "group", x = c(inten, incon)), data = df, test = F, total = F)

It works! Thank you!
