### ISSUE TITLE
Option to drop cumulative frequencies, percentages in freqlist

### ISSUE THREAD

**Issue by JohnHendrickx** [mayoverse/arsenal#360]
Many thanks for the great arsenal package! One feature I would like to see is an option to exclude cumulative frequencies and percentages in `freqlist`. Would that be much trouble?

**Comment by bethatkinson** [comment]
What I often do is use as.data.frame(freqlist()) then print out the desired columns.  But I agree that adding options to exclude these variables would make sense in the long-term.
________________________________
From: John Hendrickx ***@***.***>
Sent: Tuesday, February 7, 2023 4:28 AM
To: mayoverse/arsenal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [mayoverse/arsenal] Option to drop cumulative frequencies, percentages in freqlist (Issue #360)


Many thanks for the great arsenal package! One feature I would like to see is an option to exclude cumulative frequencies and percentages in freqlist. Would that be much trouble?

**Comment by eheinzen** [comment]
It's not documented well, but something like this should do the trick:

```
> library(arsenal)
> data(mockstudy)
> summary(freqlist(~ sex + arm, data = mockstudy))


|sex    |Treatment Arm | Freq| Cumulative Freq| Percent| Cumulative Percent|
|:------|:-------------|----:|---------------:|-------:|------------------:|
|Male   |A: IFL        |  277|             277|   18.48|              18.48|
|       |F: FOLFOX     |  411|             688|   27.42|              45.90|
|       |G: IROX       |  228|             916|   15.21|              61.11|
|Female |A: IFL        |  151|            1067|   10.07|              71.18|
|       |F: FOLFOX     |  280|            1347|   18.68|              89.86|
|       |G: IROX       |  152|            1499|   10.14|             100.00|

> summary(freqlist(~ sex + arm, data = mockstudy)[c("sex", "arm", "Freq")])


|sex    |Treatment Arm | Freq|
|:------|:-------------|----:|
|Male   |A: IFL        |  277|
|       |F: FOLFOX     |  411|
|       |G: IROX       |  228|
|Female |A: IFL        |  151|
|       |F: FOLFOX     |  280|
|       |G: IROX       |  152|
```
